import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import { Button, Container } from "@mui/material";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Container>
          <nav className="sticky py-2 justify-between flex gap-2">
            <div className="flex gap-1">
              <Button variant="outlined">
                <Link href={"/"}>Home</Link>
              </Button>
              <Button variant="outlined">
                <Link href={"/about"}>About</Link>
              </Button>
            </div>
            <div className="flex gap-1">
              <Button variant="text" className="text-green-500 font-bold">
                <Link href={"/register"}>Join</Link>
              </Button>
            </div>
          </nav>
        </Container>
        {children}
      </body>
    </html>
  );
}
